// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Northwind.WebApi.Model.Models;

public partial class AdmUser
{
    [Key]
    [Column("UserID")]
    public int UserId { get; set; }

    [Required]
    [StringLength(50)]
    public string FirstName { get; set; }

    [Required]
    [StringLength(50)]
    public string LastName { get; set; }

    [Required]
    [StringLength(50)]
    public string EmailAddress { get; set; }

    [Required]
    [StringLength(100)]
    public string Password { get; set; }

    [Column("RoleID")]
    public int RoleId { get; set; }

    [MaxLength(16)]
    public byte[] Salt { get; set; }

    public Guid Activationcode { get; set; }

    public bool EmailVerified { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateActivation { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<RefreshToken> RefreshTokens { get; } = new List<RefreshToken>();

    [ForeignKey("RoleId")]
    [InverseProperty("AdmUsers")]
    public virtual Role Role { get; set; }
}