// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Northwind.WebApi.Model.Models;

[Keyless]
[Table("Adr_Countries")]
public partial class AdrCountry
{
    public int Id { get; set; }

    [StringLength(50)]
    public string Code { get; set; }

    [StringLength(250)]
    public string Name { get; set; }
}