// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Northwind.WebApi.Model.Models;

[Keyless]
[Table("Adr_Cities")]
public partial class AdrCity
{
    public int Id { get; set; }

    [StringLength(250)]
    public string Name { get; set; }

    [StringLength(10)]
    public string AdminCode { get; set; }

    [Column(TypeName = "text")]
    public string AlternateName { get; set; }

    public int CountrieId { get; set; }
}