// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Northwind.WebApi.Model.Models
{
    public partial class SelectCustomerPagingResult
    {
        public int CustomerId { get; set; }
        public string CompanyName { get; set; }
        public string CustomerTitle { get; set; }
        public int? CustomerTitleId { get; set; }
        public string ContactName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public bool IsVip { get; set; }
        public int? TotalRows { get; set; }
    }
}
