// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Northwind.WebApi.Model.Models
{
    public partial class SelectCategoryPagingResult
    {
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public string catDescription { get; set; }
        public byte[] Picture { get; set; }
        public int? TotalRows { get; set; }
    }
}
