// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Northwind.WebApi.Model.Models;

[Table("Title")]
public partial class Title
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(200)]
    public string Name { get; set; }

    public int? IdTypeTitle { get; set; }

    [InverseProperty("Title")]
    public virtual ICollection<Employee> Employees { get; } = new List<Employee>();
}